---
title: "Community Building"
page-layout: article
---

## Community Building

I am committed to fostering inclusive, collaborative, and engaging communities within academic and extracurricular settings. My efforts have centered on supporting student well-being, interdisciplinary dialogue, and applied learning across different domains.

As part of my contribution to the growth of computational social science in South Korea, I served as a Teaching Assistant at the inaugural [Summer Institute in Computational Social Science (SICSS)](https://sicss.io/) in [South Korea](https://sicss.io/2022/korea/), co-hosted by KAIST and KDI School in 2022.

I also co-founded and served as the first head of the KDI School Ph.D. Club, helping to establish a peer support network for doctoral students. In parallel, I founded the KDI School Hapkido Club and led efforts to promote physical and mental discipline through martial arts training. I have also volunteered to teach Hapkido to children, encouraging values of respect, teamwork, and perseverance.

These experiences reflect my dedication to nurturing both academic and personal growth within my communities.
